name: "NPM multi publish"
description: "Publishes multiple tarball files to NPM registry."
author: "Reactway"
inputs:
    path:
        required: false
        description: "Working folder that contains tarballs."
        default: "."
    registry:
        required: true
        description: "NPM registry"
        default: registry.npmjs.org
    token:
        required: true
        description: Registry token
    access:
        required: false
        description: "Tells the registry whether this package should be published as public or restricted. Only applies to scoped packages, which default to restricted. If you don’t have a paid account, you must publish with --access public to publish scoped packages."
        default: public
    dryRun:
        required: false
        description: Dry-run
        default: "false"
    useTags:
        required: false
        description: 'Use generated tags from tarball name. e.g."package-1.0.0-alpha.2.tgz" -> "alpha". "--tag <tag>". Registers the published package with the given tag, such that `npm install @` will install this version. By default, `npm publish` updates and `npm install` installs the `latest` tag. See `npm-dist-tag` for details about tags.'
        default: "false"
runs:
    using: "node12"
    main: "dist/index.js"
